pipeline:
  name: axiom-cms-pr
  identifier: axiomcmspr
  projectIdentifier: OldGitSyncProj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: approval_stage_1
        identifier: approval_stage_1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval_step_1
                  identifier: approval_step_1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
